[package]
name = "lean-gym"
version = "0.1"
lean_version = "leanprover-community/lean:3.30.0"
path = "src"

[dependencies]
mathlib = { git = "https://github.com/leanprover-community/mathlib", rev = "9a8dcb9be408e7ae8af9f6832c08c021007f40ec" }
minif2f = { git = "https://github.com/openai/miniF2F.git", rev = "61a6e0dbc171321828f8d23d117e725af410d0ac" }
lean-gptf = { git = "https://github.com/jesse-michael-han/lean-gptf", rev = "a1a09952e0caa2f78ca104934c5d354322db11af" }
